### ISSUE TITLE
Crash when right clicking with the quiver

### ISSUE THREAD

**Issue by CipherUnknown** [theishiopian/Parrying#34] opened 2022-07-09 00:29 UTC
Minecraft version: 1.18.2
Forge Version: 40.1.54
Parry This! version: 1.18.2-2.5

Crash Log: https://pastebin.com/wdx65Q4Z

When I held the quiver in my hand and I right clicked it, the game just crashed. It contained a stack and something arrows as I got it from killing a pillager while testing some things.

Heres the mod list:
> Ars Nouveau - version 2.6.3
> AttributeFix - version 14.0.2
>Curios API - version 5.0.7.1
> Feature NBT Deadlock be gone - version 2.0.0
> FerriteCore - version 4.2.1
> Forbidden and Arcanus - version 2.0.0
> GeckoLib - version 3.0.28
> Just Enough Items - version 9.7.0.209
> Just Enough Resources - verssion 0.14.1.171
> LazyDataFixerUpper - version 1.0
> Majrsuz's Library - version 2.7.2
> Majrusz's Progressive Difficulty - version 1.4.2
> Parry This! - version 2.5
> Patchouli - 71.1
> Reliquary Reincarnations - 2.0.8.1139
> Rubidium - 0.5.2a
> Spark - 1.9.11
> Valhelsia Core - 0.3.1
>When Dungeons Arise - 2.1.50d-beta

**Comment by theishiopian** [comment] 2022-07-09 05:49
Duplicate of #30

**Closed as completed by theishiopian** 2022-07-09 05:49 UTC
