### ISSUE TITLE
Game crashes when COFH core is installed when attempting to use a quiver or left clicking with a filled scabbard in hand

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [theishiopian/Parrying#31] opened 2022-07-08 16:07 UTC
**Crash Reports: https://gist.github.com/NJL5390/6ec1f9b334125c74f94198b3d25b992d**

Forge Version: 40.1.54
Minecraft: 1.18.2
Parrying: 2.5
COFH Core: 1.6.4.21

Hi again,

Just found a couple more crashes in relation to COFH core. Note I have attached **two** crash reports as these seem to be two separate crashes (one related to the scabbard and one related to the quiver). 

If I can be of any assistance in relation to these two crashes feel free to let me know and I will help out in whatever testing is needed whenever I can.

Thanks again for the great mod.

EDIT: Love the sound design for this mod btw!

**Comment by theishiopian** [comment] 2022-07-08 19:50
Duplicate of #30, will fix together

**Closed as completed by theishiopian** 2022-07-08 19:50 UTC
