### ISSUE TITLE
Crashing upon opening config/keybinds

### ISSUE THREAD

**Issue by Demizilla** [theishiopian/Parrying#24] opened 2022-03-10 21:15 UTC
1.18.1, Accessing most config menus in the mod options and the keybind menu immediately crashes the game, seems to be an issue with the tag two_handed_weapons.
[crash-2022-03-10_21.12.31-client.txt](https://github.com/theishiopian/Parrying/files/8227224/crash-2022-03-10_21.12.31-client.txt)

**Comment by theishiopian** [comment] 2022-03-14 01:12
Duplicate of #21

**Closed as completed by theishiopian** 2022-03-14 01:12 UTC
