### ISSUE TITLE
IllegalStateException: Tag parrying:two_handed_weapons used before it was bound

### ISSUE THREAD

**Issue by DaftTheMonkeMan** [theishiopian/Parrying#27] opened 2022-06-03 00:23 UTC
i'm trying to apply a resource pack and my game keeps crashing

crash log:https://pastebin.com/1piKGQE7

**Comment by theishiopian** [comment] 2022-06-06 15:28
Duplicate of #21

**Closed as completed by theishiopian** 2022-06-06 15:28 UTC
